version: '3'
services:
  app:
    container_name: number-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped